"""empty message

Revision ID: 0531b9d01cfa
Revises: 42fe430de06f
Create Date: 2024-06-03 22:49:15.164398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0531b9d01cfa'
down_revision = '42fe430de06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')
        batch_op.drop_column('location')
        batch_op.drop_column('dob')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
