"""empty message

Revision ID: e068164f54ce
Revises: f72ee7ae813b
Create Date: 2024-06-13 22:19:54.806172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e068164f54ce'
down_revision = 'f72ee7ae813b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.drop_column('endTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
